export { default as JButton } from '@/components/JButton.vue'
export { default as JContainer } from '@/components/JContainer.vue'
export { default as JImage } from '@/components/JImage.vue'
export { default as JPagination } from '@/components/JPagination.vue'
export { default as JProgress } from '@/components/JProgress.vue'
export { default as JTable } from '@/components/JTable.vue'
export { default as JTableHeader } from '@/components/JTableHeader.vue'
